export const enPhrases = [
  "Time to shut down work!\nIt's %time% in %country%.",
  "Disconnecting in progress:\n%time% in %country%.",
  "Work done for the day:\n%time% in %country%.",
  "Time to free the mind:\n%time% in %country%.",
  "Bid work farewell today!\nIt's %time% in %country%.",
  "Relaxation in progress:\n%time% in %country%.",
  "Well-deserved free time!\n%time% in %country%.",
  "Time to embrace laziness:\n%time% in %country%.",
  "Time to leave the desk!\nIt's %time% in %country%.",
  "Disconnection activated:\n%time% in %country%.",
  "Time to forget emails!\n%time% in %country%.",
  "Relax and disconnect:\n%time% in %country%.",
  "Time to take care of yourself:\n%time% in %country%.",
  "It's over for today!\nIt's %time% in %country%.",
  "Detach from the screen:\n%time% in %country%.",
  "Time to be free from tasks:\n%time% in %country%.",
  "Time to recharge happiness:\n%time% in %country%.",
  "Enjoy the rest of the day!\nIt's %time% in %country%.",
  "Time to be a happy idler:\n%time% in %country%.",
  "Clocking out:\n%time% in %country%.",
  "Time to switch off:\n%time% in %country%.",
  "Work mode: off.\nIt's %time% in %country%.",
  "Time to make relaxation a priority:\n%time% in %country%.",
  "Unwind and let go:\n%time% in %country%.",
  "Time to embrace leisure:\n%time% in %country%.",
  "End of the line:\n%time% in %country%.",
  "Switching to relaxation mode:\n%time% in %country%.",
  "It's %time% in %country%,\n and the office lights are off.",
  "Time to say goodbye to tasks:\n%time% in %country%.",
  "Shift to chill gear:\n%time% in %country%.",
  "Time to unwind and unplug:\n%time% in %country%.",
  "Leaving the grind behind:\n%time% in %country%.",
  "Time to let go of stress:\n%time% in %country%.",
  "Transition to relaxation:\n%time% in %country%.",
  "It's %time% in %country%,\nand work can wait.",
  "Time to prioritize self-care:\n%time% in %country%.",
  "Logging off:\n%time% in %country%.",
  "Time to enjoy life:\n%time% in %country%.",
  "Shift to leisure mode:\n%time% in %country%.",
  "Time to embrace the couch:\n%time% in %country%.",
  "Work's over, fun begins:\n%time% in %country%.",
  "Time to swap work shoes for slippers:\n%time% in %country%.",
  "No more spreadsheets:\n%time% in %country%.",
  "Time to be the boss of relaxation:\n%time% in %country%.",
  "Work's paused, fun's resumed:\n%time% in %country%.",
  "Time to swap coffee for wine:\n%time% in %country%.",
  "No more meetings today:\n%time% in %country%.",
  "Time to catch some sun:\n%time% in %country%.",
  "Work's out, you're free:\n%time% in %country%.",
  "Time to dance in the living room:\n%time% in %country%.",
  "No more emails, just dreams:\n%time% in %country%.",
  "Time to enjoy the little things:\n%time% in %country%.",
  "Work's done, time for fun:\n%time% in %country%.",
  "Time to catch up on shows:\n%time% in %country%.",
  "No more deadlines today:\n%time% in %country%.",
  "Time to enjoy the sunset:\n%time% in %country%.",
  "Work's clocked out, you're in:\n%time% in %country%.",
  "Time for some me-time:\n%time% in %country%.",
  "No more tasks, just relax:\n%time% in %country%.",
  "Time to dive into a book:\n%time% in %country%.",
  "Work's paused, life's playing:\n%time% in %country%.",
  "Time to enjoy nature's beauty:\n%time% in %country%.",
  "No more calls, just calm:\n%time% in %country%.",
  "Time to listen to your favorite tunes:\n%time% in %country%.",
  "Work's muted, music's on:\n%time% in %country%.",
  "Time to cook something yummy:\n%time% in %country%.",
  "No more screens, just scenes:\n%time% in %country%.",
  "Time to take a long bath:\n%time% in %country%.",
  "Work's out, stars are in:\n%time% in %country%.",
  "Time to light some candles:\n%time% in %country%.",
  "No more typing, just chilling:\n%time% in %country%.",
  "Time to pet your furry friend:\n%time% in %country%.",
  "Work's done, playtime's on:\n%time% in %country%.",
  "Time to stretch and breathe:\n%time% in %country%.",
  "No more hustle, just flow:\n%time% in %country%.",
  "Time to doodle and dream:\n%time% in %country%.",
  "Work's off, adventure's on:\n%time% in %country%.",
  "Time to gaze at the stars:\n%time% in %country%.",
  "No more alarms, just peace:\n%time% in %country%.",
  "Time to sip some tea:\n%time% in %country%.",
  "Work's paused, passion's playing:\n%time% in %country%.",
  "Time to laugh out loud:\n%time% in %country%.",
  "No more charts, just arts:\n%time% in %country%.",
  "Time to dive into hobbies:\n%time% in %country%.",
  "Work's done, creativity's on:\n%time% in %country%.",
  "Time to explore new things:\n%time% in %country%.",
  "No more pings, just zings:\n%time% in %country%.",
  "Time to cherish the moment:\n%time% in %country%.",
  "Work's out, joy's in:\n%time% in %country%.",
  "Time to be in the present:\n%time% in %country%.",
];

export const phrases: Record<string, string[]> = {
  en: enPhrases,
  es: [
    "¡Hora de jugar, ese nivel no se va a pasar solo!\nSon las %time% en %country%.",
    "Desconexión en progreso:\n%time% en %country%.",
    "Trabajo terminado por hoy:\n%time% en %country%.",
    "Es hora de abrazar la pereza:\n%time% en %country%.",
    "¡Saca la mano de ahí. carajo!\nSon las %time% en %country%.",
    "Hora de reportar problemas de conexión:\n%time% en %country%.",
    "¡Olvidate de los correos!\nSon las %time% en %country%.",
    "Hora de ser un tipo chill de cojones:\n%time% en %country%.",
    "Es hora de cuidarte a vos mismo:\n%time% en %country%.",
    "¡A disfrutar el resto del día!\nSon las %time% en %country%.",
    "Momento de ser un vago feliz:\n%time% en %country%.",
    "¡Cerrando sesión... y abriendo una birrita!\n%time% en %country%.",
    "Esos problemas pueden esperar:\nSon las %time% en %country%.",
    "¡Prioridad a la relajación!\n%time% en %country%.",
    "Desconectate y soltá el estrés:\n%time% en %country%.",
    "Punto final del día:\n%time% en %country%.",
    "Son las %time% en %country%...\ny las luces de la oficina están apagadas.",
    "Hora de decirle adiós a las tareas:\n%time% en %country%.",
    "Cambiando a modo chill:\n%time% en %country%.",
    "Transición hacia la relajación:\n%time% en %country%.",
    "Son las %time% en %country%...\ny el trabajo puede esperar.",
    "¡Es hora de abrazar el sillón!\n%time% en %country%.",
    "¡Cambiá los zapatos de trabajo por pantuflas!\n%time% en %country%.",
    "¡Sé el jefe de tu propia relajación!\n%time% en %country%.",
    "Hora de cambiar el café por un vinito:\n%time% en %country%.",
    "¡Sin más reuniones por hoy!\n%time% en %country%.",
    "El trabajo terminó, sos libre:\n%time% en %country%.",
    "Dobby tiene un calcetín:\n%time% en %country%.",
    "Momento de ponerse al día con las series:\n%time% en %country%.",
    "No más fechas límite hoy:\n%time% en %country%.",
    "CHAVALEEEEEES, ¡que e' viernes!\n%time% en %country%.",
    "Como dice Virginia Lagos: ¿Sale un vinito?\n%time% en %country%.",
    "¡Hasta la vista, baby!\n%time% en %country%.",
    "¡Por fin se fue el tóxico (el trabajo, obvio)!\n%time% en %country%.",
    "¡Que comiencen los chismes! \n%time% en %country%.",
    "¡Un aplauso para el asador... y para el que se desconecta!\n%time% en %country%.",
    "Y ahora... ¡la magia de la desconexión!\n%time% en %country%.",
    '¡Que alguien ponga "Despechá" de Rosalía YA!\n%time% en %country%.',
    "¿Y si ponemos unas de esas canciones que dan sed?\n%time% en %country%.",
    '¡Modo "no me hablen de trabajo" activado!\n%time% en %country%.',
    "¡Los dioses del descanso te convocan!\n%time% en %country%.",
    "¡Esto se va descontrolaaaaaar!\n%time% en %country%.",
    "¡El verdadero jefe me dio permiso de descansar (soy yo)!\n%time% en %country%.",
    "Se cierra la laptop, se abre el after.\n%time% en %country%.",
    "Trabajo no sos vos, soy yo...\n%time% en %country%.",
    "¿No te conto tu mamá de la nueva novela turca que está buenísima?\n%time% en %country%.",
    "¿After? Yendo no, llegando.\n%time% en %country%.",
    "Si ves esto, es porque ya estoy desconectado.\n%time% en %country%.",
    "La silla de la oficina me extrañará, pero no es recíproco.\n%time% en %country%.",
    'Que nadie diga "reunión" porque hoy no hay.\n%time% en %country%.',
    "Lo unico que se debe planificar ahora es el after.\n%time% en %country%.",
    "¡Señoras y señores, terminó la función laboral!\n%time% en %country%.",
    "¡Uy! Se cortó la luz.\n%time% en %country%.",
    "Mi compu está actualizando Windows... puede tardar.\n%time% en %country%.",
    "¡Mi compu está súper lenta, no sé qué le pasa! \n%time% en %country%.",
    "Mi vecino está haciendo ruido, no escucho nada.\n%time% en %country%.",
    "¡Bateria laboral agotada!\n%time% en %country%.",
  ],
  it: [
    "È ora di giocare, quel livello non si passerà da solo!\nSono le %time% in %country%.",
    "Disconnessione in corso:\n%time% in %country%.",
    "Lavoro finito per oggi:\n%time% in %country%.",
    "È ora di abbracciare la pigrizia:\n%time% in %country%.",
    "È ora di segnalare problemi di connessione:\n%time% in %country%.",
    "Dimentica le email!\nSono le %time% in %country%.",
    "È il momento di essere super chill:\n%time% in %country%.",
    "È ora di prenderti cura di te stesso:\n%time% in %country%.",
    "Goditi il resto della giornata!\nSono le %time% in %country%.",
    "È il momento di essere un pigro felice:\n%time% in %country%.",
    "Disconnessione in corso... e si apre una birretta!\n%time% in %country%.",
    "Quei problemi possono aspettare:\nSono le %time% in %country%.",
    "Priorità al relax!\n%time% in %country%.",
    "Disconnettiti e lascia andare lo stress:\n%time% in %country%.",
    "Fine della giornata:\n%time% in %country%.",
    "Sono le %time% in %country%...\ne le luci dell'ufficio sono spente.",
    "È ora di dire addio ai compiti:\n%time% in %country%.",
    "Passando alla modalità chill:\n%time% in %country%.",
    "Transizione verso il relax:\n%time% in %country%.",
    "Sono le %time% in %country%...\ne il lavoro può aspettare.",
    "È ora di abbracciare il divano!\n%time% in %country%.",
    "Cambia le scarpe da lavoro con le pantofole!\n%time% in %country%.",
    "Diventa il capo del tuo relax!\n%time% in %country%.",
    "È ora di cambiare il caffè con un bicchiere di vino:\n%time% in %country%.",
    "Niente più riunioni per oggi!\n%time% in %country%.",
    "Il lavoro è finito, sei libero:\n%time% in %country%.",
    "Dobby ha ricevuto un calzino:\n%time% in %country%.",
    "È il momento di recuperare le serie TV:\n%time% in %country%.",
    "Niente più scadenze per oggi:\n%time% in %country%.",
    "RAGAZZIIII, è venerdì!\n%time% in %country%.",
    "Finalmente se n'è andato il tossico (il lavoro, ovviamente)!\n%time% in %country%.",
    "Che inizino i gossip!\n%time% in %country%.",
    "E ora... la magia della disconnessione!\n%time% in %country%.",
    "E se mettessimo una di quelle canzoni che fanno venire sete?\n%time% in %country%.",
    'Modalità "non parlatemi di lavoro" attivata!\n%time% in %country%.',
    "Gli dei del riposo ti stanno chiamando!\n%time% in %country%.",
    "Il vero capo mi ha dato il permesso di riposare (sono io)!\n%time% in %country%.",
    "Il laptop si chiude, l'after si apre.\n%time% in %country%.",
    "Lavoro, non sei tu, sono io...\n%time% in %country%.",
    "Non te l'ha detto tua mamma della nuova serie turca che è pazzesca?\n%time% in %country%.",
    "Se stai leggendo questo, vuol dire che sono già offline.\n%time% in %country%.",
    "La sedia dell'ufficio sentirà la mia mancanza, ma non è reciproco.\n%time% in %country%.",
    'Che nessuno dica "riunione" perché oggi non ce ne sono.\n%time% in %country%.',
    "L'unica cosa da pianificare ora è l'after.\n%time% in %country%.",
    "Signore e signori, lo show lavorativo è finito!\n%time% in %country%.",
    "Ops! È saltata la corrente.\n%time% in %country%.",
    "Il mio PC sta aggiornando Windows... potrebbe volerci un po'.\n%time% in %country%.",
    "Il mio PC è lentissimo, non so cosa gli prenda!\n%time% in %country%.",
    "Il mio vicino sta facendo casino, non sento niente.\n%time% in %country%.",
    "Batteria lavorativa esaurita!\n%time% in %country%.",
  ],
  fr: [
    "Il est temps d'éteindre le travail !\nIl est %time% en %country%.",
    "Déconnexion en cours:\n%time% en %country%.",
    "Travail terminé pour la journée:\n%time% en %country%.",
    "Il est temps de libérer l'esprit:\n%time% en %country%.",
    "Dis adieu au boulot aujourd'hui !\nIl est %time% en %country%.",
    "Détente en cours:\n%time% en %country%.",
    "Du repos bien mérité !\n%time% en %country%.",
    "Il est temps d'assumer la paresse:\n%time% en %country%.",
    "Quitte le bureau !\nIl est %time% en %country%.",
    "Déconnexion activée:\n%time% en %country%.",
    "Oublie les emails !\n%time% en %country%.",
    "Détends-toi et déconnecte:\n%time% en %country%.",
    "Prends soin de toi:\n%time% en %country%.",
    "C'est fini pour aujourd'hui !\nIl est %time% en %country%.",
    "Lâche l'écran:\n%time% en %country%.",
  ],
  de: [
    "Zeit, die Arbeit zu beenden!\nEs ist %time% in %country%.",
    "Trennung läuft:\n%time% in %country%.",
    "Feierabend für heute:\n%time% in %country%.",
    "Zeit, den Kopf frei zu bekommen:\n%time% in %country%.",
    "Verabschiede dich heute von der Arbeit!\nEs ist %time% in %country%.",
    "Entspannung läuft:\n%time% in %country%.",
    "Verdiente Freizeit!\n%time% in %country%.",
    "Zeit für Faulheit:\n%time% in %country%.",
    "Raus vom Schreibtisch!\nEs ist %time% in %country%.",
    "Trennung aktiviert:\n%time% in %country%.",
    "Vergiss E-Mails!\n%time% in %country%.",
    "Entspanne und trenne dich:\n%time% in %country%.",
    "Kümmere dich um dich selbst:\n%time% in %country%.",
    "Für heute ist Schluss!\nEs ist %time% in %country%.",
    "Weg vom Bildschirm:\n%time% in %country%.",
  ],
  pt: [
    "Hora de desligar o trabalho!\nSão %time% em %country%.",
    "Desconectando:\n%time% em %country%.",
    "Trabalho encerrado por hoje:\n%time% em %country%.",
    "Hora de liberar a mente:\n%time% em %country%.",
    "Diga adeus ao trabalho hoje!\nSão %time% em %country%.",
    "Relaxamento em andamento:\n%time% em %country%.",
    "Tempo livre merecido!\n%time% em %country%.",
    "Hora de abraçar a preguiça:\n%time% em %country%.",
    "Saia da mesa!\nSão %time% em %country%.",
    "Desconexão ativada:\n%time% em %country%.",
    "Esqueça os e-mails!\n%time% em %country%.",
    "Relaxe e desconecte:\n%time% em %country%.",
    "Cuide de si mesmo:\n%time% em %country%.",
    "Por hoje acabou!\nSão %time% em %country%.",
    "Longe da tela:\n%time% em %country%.",
  ],
  zh: [
    "该结束工作了！\n现在是 %country%的%time%.",
    "正在断开连接:\n%country%的%time%.",
    "今天的工作完成了:\n%country%的%time%.",
    "是时候放空大脑:\n%country%的%time%.",
    "今天向工作说再见！\n现在是 %country%的%time%.",
    "放松进行中:\n%country%的%time%.",
    "值得的休息时间！\n%country%的%time%.",
    "是时候拥抱懒惰:\n%country%的%time%.",
    "离开桌前吧！\n现在是 %country%的%time%.",
    "断线已激活:\n%country%的%time%.",
    "忘掉邮件吧！\n%country%的%time%.",
    "放松并断开:\n%country%的%time%.",
    "照顾好自己:\n%country%的%time%.",
    "今天就到此结束！\n现在是 %country%的%time%.",
    "远离屏幕:\n%country%的%time%.",
  ],
  ja: [
    "仕事を終了する時間です！\n%country%では %time% です。",
    "接続解除中:\n%country%では %time% です。",
    "今日の仕事は終わり:\n%country%では %time% です。",
    "頭を解放する時間:\n%country%では %time% です。",
    "今日の仕事にさよなら！\n%country%では %time% です。",
    "リラックス中:\n%country%では %time% です。",
    "十分な自由時間！\n%country%では %time% です。",
    "怠ける時間です:\n%country%では %time% です。",
    "机を離れよう！\n%country%では %time% です。",
    "切断完了:\n%country%では %time% です。",
    "メールは忘れて！\n%country%では %time% です。",
    "リラックスして切断:\n%country%では %time% です。",
    "自分を大切に:\n%country%では %time% です。",
    "今日はこれでおしまい！\n%country%では %time% です。",
    "画面から離れて:\n%country%では %time% です。",
  ],
};
