export const phrases = [
  "Time to shut down work!\nIt's %time% in %country%.",
  "Disconnecting in progress:\n%time% in %country%.",
  "Work done for the day:\n%time% in %country%.",
  "Time to free the mind:\n%time% in %country%.",
  "Bid work farewell today!\nIt's %time% in %country%.",
  "Relaxation in progress:\n%time% in %country%.",
  "Well-deserved free time!\n%time% in %country%.",
  "Time to embrace laziness:\n%time% in %country%.",
  "Time to leave the desk!\nIt's %time% in %country%.",
  "Disconnection activated:\n%time% in %country%.",
  "Time to forget emails!\n%time% in %country%.",
  "Relax and disconnect:\n%time% in %country%.",
  "Time to take care of yourself:\n%time% in %country%.",
  "It's over for today!\nIt's %time% in %country%.",
  "Detach from the screen:\n%time% in %country%.",
  "Time to be free from tasks:\n%time% in %country%.",
  "Time to recharge happiness:\n%time% in %country%.",
  "Enjoy the rest of the day!\nIt's %time% in %country%.",
  "Time to be a happy idler:\n%time% in %country%.",
  "Clocking out:\n%time% in %country%.",
  "Time to switch off:\n%time% in %country%.",
  "Work mode: off.\nIt's %time% in %country%.",
  "Time to make relaxation a priority:\n%time% in %country%.",
  "Unwind and let go:\n%time% in %country%.",
  "Time to embrace leisure:\n%time% in %country%.",
  "End of the line:\n%time% in %country%.",
  "Switching to relaxation mode:\n%time% in %country%.",
  "It's %time% in %country%,\n and the office lights are off.",
  "Time to say goodbye to tasks:\n%time% in %country%.",
  "Shift to chill gear:\n%time% in %country%.",
  "Time to unwind and unplug:\n%time% in %country%.",
  "Leaving the grind behind:\n%time% in %country%.",
  "Time to let go of stress:\n%time% in %country%.",
  "Transition to relaxation:\n%time% in %country%.",
  "It's %time% in %country%,\nand work can wait.",
  "Time to prioritize self-care:\n%time% in %country%.",
  "Logging off:\n%time% in %country%.",
  "Time to enjoy life:\n%time% in %country%.",
  "Shift to leisure mode:\n%time% in %country%.",
  "Time to embrace the couch:\n%time% in %country%.",
  "Work's over, fun begins:\n%time% in %country%.",
  "Time to swap work shoes for slippers:\n%time% in %country%.",
  "No more spreadsheets:\n%time% in %country%.",
  "Time to be the boss of relaxation:\n%time% in %country%.",
  "Work's paused, fun's resumed:\n%time% in %country%.",
  "Time to swap coffee for wine:\n%time% in %country%.",
  "No more meetings today:\n%time% in %country%.",
  "Time to catch some sun:\n%time% in %country%.",
  "Work's out, you're free:\n%time% in %country%.",
  "Time to dance in the living room:\n%time% in %country%.",
  "No more emails, just dreams:\n%time% in %country%.",
  "Time to enjoy the little things:\n%time% in %country%.",
  "Work's done, time for fun:\n%time% in %country%.",
  "Time to catch up on shows:\n%time% in %country%.",
  "No more deadlines today:\n%time% in %country%.",
  "Time to enjoy the sunset:\n%time% in %country%.",
  "Work's clocked out, you're in:\n%time% in %country%.",
  "Time for some me-time:\n%time% in %country%.",
  "No more tasks, just relax:\n%time% in %country%.",
  "Time to dive into a book:\n%time% in %country%.",
  "Work's paused, life's playing:\n%time% in %country%.",
  "Time to enjoy nature's beauty:\n%time% in %country%.",
  "No more calls, just calm:\n%time% in %country%.",
  "Time to listen to your favorite tunes:\n%time% in %country%.",
  "Work's muted, music's on:\n%time% in %country%.",
  "Time to cook something yummy:\n%time% in %country%.",
  "No more screens, just scenes:\n%time% in %country%.",
  "Time to take a long bath:\n%time% in %country%.",
  "Work's out, stars are in:\n%time% in %country%.",
  "Time to light some candles:\n%time% in %country%.",
  "No more typing, just chilling:\n%time% in %country%.",
  "Time to pet your furry friend:\n%time% in %country%.",
  "Work's done, playtime's on:\n%time% in %country%.",
  "Time to stretch and breathe:\n%time% in %country%.",
  "No more hustle, just flow:\n%time% in %country%.",
  "Time to doodle and dream:\n%time% in %country%.",
  "Work's off, adventure's on:\n%time% in %country%.",
  "Time to gaze at the stars:\n%time% in %country%.",
  "No more alarms, just peace:\n%time% in %country%.",
  "Time to sip some tea:\n%time% in %country%.",
  "Work's paused, passion's playing:\n%time% in %country%.",
  "Time to laugh out loud:\n%time% in %country%.",
  "No more charts, just arts:\n%time% in %country%.",
  "Time to dive into hobbies:\n%time% in %country%.",
  "Work's done, creativity's on:\n%time% in %country%.",
  "Time to explore new things:\n%time% in %country%.",
  "No more pings, just zings:\n%time% in %country%.",
  "Time to cherish the moment:\n%time% in %country%.",
  "Work's out, joy's in:\n%time% in %country%.",
  "Time to be in the present:\n%time% in %country%.",
];
