export const phrases = [
  "Time to shut down work!\nIt's %time% in %country%.",
  "Disconnecting in progress:\n%time% in %country%.",
  "Work done for the day:\n%time% in %country%.",
  "Time to free the mind:\n%time% in %country%.",
  "Bid work farewell today!\nIt's %time% in %country%.",
  "Relaxation in progress:\n%time% in %country%.",
  "Well-deserved free time!\n%time% in %country%.",
  "Time to embrace laziness:\n%time% in %country%.",
  "Time to leave the desk!\nIt's %time% in %country%.",
  "Disconnection activated:\n%time% in %country%.",
  "Time to forget emails!\n%time% in %country%.",
  "Relax and disconnect:\n%time% in %country%.",
  "Time to take care of yourself:\n%time% in %country%.",
  "It's over for today!\nIt's %time% in %country%.",
  "Detach from the screen:\n%time% in %country%.",
  "Time to be free from tasks:\n%time% in %country%.",
  "Time to recharge happiness:\n%time% in %country%.",
  "Enjoy the rest of the day!\nIt's %time% in %country%.",
  "Time to be a happy idler:\n%time% in %country%.",
  "Clocking out:\n%time% in %country%.",
  "Time to switch off:\n%time% in %country%.",
  "Work mode: off.\nIt's %time% in %country%.",
  "Time to make relaxation a priority:\n%time% in %country%.",
  "Unwind and let go:\n%time% in %country%.",
  "Time to embrace leisure:\n%time% in %country%.",
  "End of the line:\n%time% in %country%.",
  "Switching to relaxation mode:\n%time% in %country%.",
  "It's %time% in %country%,\n and the office lights are off.",
  "Time to say goodbye to tasks:\n%time% in %country%.",
  "Shift to chill gear:\n%time% in %country%.",
  "Time to unwind and unplug:\n%time% in %country%.",
  "Leaving the grind behind:\n%time% in %country%.",
  "Time to let go of stress:\n%time% in %country%.",
  "Transition to relaxation:\n%time% in %country%.",
  "It's %time% in %country%,\nand work can wait.",
  "Time to prioritize self-care:\n%time% in %country%.",
  "Logging off:\n%time% in %country%.",
  "Time to enjoy life:\n%time% in %country%.",
  "Shift to leisure mode:\n%time% in %country%.",
];
